pipeline {
    agent any

    environment {
        ROBOT_IMAGE = "robot-tests-image"
        PLAYWRIGHT_IMAGE = "playwright-tests-image"
        SELENIUM_IMAGE = "selenium-tests-image"
    }

    stages {

        stage('Checkout du code source') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Chamseddine-svg/automation-project-saucedemo-UTS.git'
            }
        }

        stage('Build Docker images') {
            steps {
                sh '''
                # Robot Framework Docker build
                docker build -t $ROBOT_IMAGE robot_tests

                # Playwright Docker build
                docker build -t $PLAYWRIGHT_IMAGE playwright_tests

                # Selenium Docker build
                docker build -t $SELENIUM_IMAGE selenium_tests
                '''
            }
        }

        stage('Run Robot Framework tests') {
            steps {
                sh '''
                docker run --rm -v $WORKSPACE/robot-tests/reports:/opt/tests/reports $ROBOT_IMAGE
                '''
            }
        }

        stage('Run Playwright tests') {
            steps {
                sh '''
                docker run --rm -v $WORKSPACE/playwright-tests/playwright-report:/opt/tests/playwright-report $PLAYWRIGHT_IMAGE
                '''
            }
        }

        stage('Run Selenium Python tests') {
            steps {
                sh '''
                docker run --rm -v $WORKSPACE/selenium-tests/reports:/opt/tests/reports $SELENIUM_IMAGE
                '''
            }
        }
    }

    post {
        always {
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'robot-tests/reports',
                reportFiles: 'report.html',
                reportName: 'Robot Framework Report'
            ])

            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'playwright-tests/playwright-report',
                reportFiles: 'index.html',
                reportName: 'Playwright Report'
            ])

            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'selenium-tests/reports',
                reportFiles: 'report.html',
                reportName: 'Selenium Python Report'
            ])
        }
    }
}
