pipeline {
    agent any

    environment {
        ROBOT_IMAGE = "robot-tests-image"
        PLAYWRIGHT_IMAGE = "playwright-tests-image"
        SELENIUM_IMAGE = "selenium-tests-image"
    }

    stages {

        stage('Checkout du code source') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Chamseddine-svg/automation-project-saucedemo-UTS.git'
            }
        }

        stage('Build Docker images') {
            steps {
                sh '''
                docker build -t $ROBOT_IMAGE robot_tests
                docker build -t $PLAYWRIGHT_IMAGE playwright_tests
                docker build -t $SELENIUM_IMAGE selenium_tests
                '''
            }
        }

/*         stage('Run Robot Framework tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
                    sh '''
                    # Ensure reports folder exists
                    mkdir -p robot_tests/reports
                    # Run tests, allow failures
                    docker run --rm -v $(pwd):/tests $ROBOT_IMAGE \
                    robot --outputdir /tests/robot_tests/reports /tests/robot_tests
                    '''
                }
            }
        } */
/*         stage('Run Playwright tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
                    sh '''
                    mkdir -p playwright_tests/playwright-report
                    docker run --rm $PLAYWRIGHT_IMAGE \
                    npx playwright test --reporter=html --output=/tests/playwright_tests/playwright-report
                    '''
                }
            }
        }
 */
        stage('Run Selenium Python tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
                    sh '''
                    python3 -m pip install --upgrade pip
                    python3 -m pip install pytest pytest-html
                    mkdir -p selenium_tests/reports
                    docker run --rm -v $WORKSPACE/selenium_tests/reports:/tests/reports selenium-tests \
                    pytest --html=/tests/reports/report.html --self-contained-html || true
                    '''
                }
            }
        }


    }

    post {
        always {
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'robot_tests/reports',
                reportFiles: 'report.html',
                reportName: 'Robot Framework Report'
            ])

            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'playwright_tests/playwright-report',
                reportFiles: 'index.html',
                reportName: 'Playwright Report'
            ])

            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'selenium_tests/reports',
                reportFiles: 'report.html',
                reportName: 'Selenium Python Report'
            ])
        }
    }
}
